#!/usr/bin/env bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright Clairvoyant 2019
#
set -ex

function log {
  timestamp=$(date)
  echo "$timestamp: $1"       #stdout
  echo "$timestamp: $1" 1>&2; #stderr
}

# time marker for both stderr and stdout
log "Running Airflow CSD control script..."
log "Detected CDH_VERSION of [$CDH_VERSION]"

# ensure $AIRFLOW_HOME is defined
if [[ -z "$AIRFLOW_HOME" ]]; then
  log "ERROR: AIRFLOW_HOME environment variable is not set"
  exit 1
fi

# ensure $AIRFLOW_HOME exists
if [[ ! -d "$AIRFLOW_HOME" ]]; then
  mkdir -p "$AIRFLOW_HOME"
fi

# replace $1 with $2 in file $3
function replace {
  sed -i "s|${1}|${2}|g" "$3"
}

# prepare the airflow.cfg file specified in $1 by substituting placeholder variables
function prepare_airflow_cfg {
  # variables -- core
  replace "{{AIRFLOW__CORE__DAGS_FOLDER}}" "$AIRFLOW__CORE__DAGS_FOLDER" "$1"
  replace "{{AIRFLOW__CORE__BASE_LOG_FOLDER}}" "$AIRFLOW__CORE__BASE_LOG_FOLDER" "$1"
  replace "{{AIRFLOW__CORE__PLUGINS_FOLDER}}" "$AIRFLOW__CORE__PLUGINS_FOLDER" "$1"
#  replace "{{AIRFLOW__CORE__SQL_ALCHEMY_CONN}}" "$AIRFLOW__CORE__SQL_ALCHEMY_CONN" "$1"
  replace "{{AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE}}" "$AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE" "$1"
  replace "{{AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE}}" "$AIRFLOW__CORE__SQL_ALCHEMY_POOL_RECYCLE" "$1"
  replace "{{AIRFLOW__CORE__SQL_ALCHEMY_RECONNECT_TIMEOUT}}" "$AIRFLOW__CORE__SQL_ALCHEMY_RECONNECT_TIMEOUT" "$1"
  replace "{{AIRFLOW__CORE__PARALLELISM}}" "$AIRFLOW__CORE__PARALLELISM" "$1"
  replace "{{AIRFLOW__CORE__DAG_CONCURRENCY}}" "$AIRFLOW__CORE__DAG_CONCURRENCY" "$1"
  replace "{{AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION}}" "$AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION" "$1"
  replace "{{AIRFLOW__CORE__NON_POOLED_TASK_SLOT_COUNT}}" "$AIRFLOW__CORE__NON_POOLED_TASK_SLOT_COUNT" "$1"
  replace "{{AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG}}" "$AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG" "$1"
  replace "{{AIRFLOW__CORE__LOAD_EXAMPLES}}" "$AIRFLOW__CORE__LOAD_EXAMPLES" "$1"
#  replace "{{AIRFLOW__CORE__FERNET_KEY}}" "$AIRFLOW__CORE__FERNET_KEY" "$1"
  replace "{{AIRFLOW__CORE__DONOT_PICKLE}}" "$AIRFLOW__CORE__DONOT_PICKLE" "$1"
  replace "{{AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT}}" "$AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT" "$1"
  replace "{{AIRFLOW__CORE__DEFAULT_IMPERSONATION}}" "$AIRFLOW__CORE__DEFAULT_IMPERSONATION" "$1"
  replace "{{AIRFLOW__CORE__SECURITY}}" "$AIRFLOW__CORE__SECURITY" "$1"
  replace "{{AIRFLOW__CORE__SECURE_MODE}}" "$AIRFLOW__CORE__SECURE_MODE" "$1"
  replace "{{AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME}}" "$AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME" "$1"
  replace "{{AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS}}" "$AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS" "$1"
  replace "{{AIRFLOW__CORE__WORKER_PRECHECK}}" "$AIRFLOW__CORE__WORKER_PRECHECK" "$1"
  replace "{{AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE}}" "$AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE" "$1"

  # variables -- cli
  replace "{{AIRFLOW__CLI__API_CLIENT}}" "$AIRFLOW__CLI__API_CLIENT" "$1"
  replace "{{AIRFLOW__CLI__ENDPOINT_URL}}" "$AIRFLOW__CLI__ENDPOINT_URL" "$1"

  # variables -- api
  replace "{{AIRFLOW__API__AUTH_BACKEND}}" "$AIRFLOW__API__AUTH_BACKEND" "$1"

  # variables -- lineage
  replace "{{AIRFLOW__LINEAGE__BACKEND}}" "$AIRFLOW__LINEAGE__BACKEND" "$1"

  # variables -- atlas
  replace "{{AIRFLOW__ATLAS__HOST}}" "$AIRFLOW__ATLAS__HOST" "$1"
  replace "{{AIRFLOW__ATLAS__PORT}}" "$AIRFLOW__ATLAS__PORT" "$1"
  replace "{{AIRFLOW__ATLAS__USERNAME}}" "$AIRFLOW__ATLAS__USERNAME" "$1"
#  replace "{{AIRFLOW__ATLAS__PASSWORD}}" "$AIRFLOW__ATLAS__PASSWORD" "$1"

  # variables -- operators
  replace "{{AIRFLOW__OPERATORS__DEFAULT_OWNER}}" "$AIRFLOW__OPERATORS__DEFAULT_OWNER" "$1"
  replace "{{AIRFLOW__OPERATORS__DEFAULT_CPUS}}" "$AIRFLOW__OPERATORS__DEFAULT_CPUS" "$1"
  replace "{{AIRFLOW__OPERATORS__DEFAULT_RAM}}" "$AIRFLOW__OPERATORS__DEFAULT_RAM" "$1"
  replace "{{AIRFLOW__OPERATORS__DEFAULT_DISK}}" "$AIRFLOW__OPERATORS__DEFAULT_DISK" "$1"
  replace "{{AIRFLOW__OPERATORS__DEFAULT_GPUS}}" "$AIRFLOW__OPERATORS__DEFAULT_GPUS" "$1"

  # variables -- hive
  replace "{{AIRFLOW__HIVE__DEFAULT_HIVE_MAPRED_QUEUE}}" "$AIRFLOW__HIVE__DEFAULT_HIVE_MAPRED_QUEUE" "$1"

  # variables -- webserver
  replace "{{AIRFLOW__WEBSERVER__BASE_URL}}" "$AIRFLOW__WEBSERVER__BASE_URL" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_HOST}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_HOST" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_PORT}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_PORT" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT" "$1"
  replace "{{AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT}}" "$AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT" "$1"
  replace "{{AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE}}" "$AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE" "$1"
  replace "{{AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL}}" "$AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL" "$1"
#  replace "{{AIRFLOW__WEBSERVER__SECRET_KEY}}" "$AIRFLOW__WEBSERVER__SECRET_KEY" "$1"
  replace "{{AIRFLOW__WEBSERVER__WORKERS}}" "$AIRFLOW__WEBSERVER__WORKERS" "$1"
  replace "{{AIRFLOW__WEBSERVER__WORKER_CLASS}}" "$AIRFLOW__WEBSERVER__WORKER_CLASS" "$1"
  replace "{{AIRFLOW__WEBSERVER__EXPOSE_CONFIG}}" "$AIRFLOW__WEBSERVER__EXPOSE_CONFIG" "$1"
  replace "{{AIRFLOW__WEBSERVER__AUTHENTICATE}}" "$AIRFLOW__WEBSERVER__AUTHENTICATE" "$1"
  replace "{{AIRFLOW__WEBSERVER__AUTH_BACKEND}}" "$AIRFLOW__WEBSERVER__AUTH_BACKEND" "$1"
  replace "{{AIRFLOW__WEBSERVER__FILTER_BY_OWNER}}" "$AIRFLOW__WEBSERVER__FILTER_BY_OWNER" "$1"
  replace "{{AIRFLOW__WEBSERVER__OWNER_MODE}}" "$AIRFLOW__WEBSERVER__OWNER_MODE" "$1"
  replace "{{AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW}}" "$AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW" "$1"
  replace "{{AIRFLOW__WEBSERVER__DAG_ORIENTATION}}" "$AIRFLOW__WEBSERVER__DAG_ORIENTATION" "$1"
  replace "{{AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC}}" "$AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC" "$1"
  replace "{{AIRFLOW__WEBSERVER__HIDE_PAUSED_DAGS_BY_DEFAULT}}" "$AIRFLOW__WEBSERVER__HIDE_PAUSED_DAGS_BY_DEFAULT" "$1"
  replace "{{AIRFLOW__WEBSERVER__PAGE_SIZE}}" "$AIRFLOW__WEBSERVER__PAGE_SIZE" "$1"
  replace "{{AIRFLOW__WEBSERVER__RBAC}}" "$AIRFLOW__WEBSERVER__RBAC" "$1"
  replace "{{AIRFLOW__WEBSERVER__NAVBAR_COLOR}}" "$AIRFLOW__WEBSERVER__NAVBAR_COLOR" "$1"
  replace "{{AIRFLOW__WEBSERVER__DEFAULT_DAG_RUN_DISPLAY_NUMBER}}" "$AIRFLOW__WEBSERVER__DEFAULT_DAG_RUN_DISPLAY_NUMBER" "$1"
  replace "{{AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX}}" "$AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX" "$1"
  replace "{{AIRFLOW__WEBSERVER__COOKIE_SECURE}}" "$AIRFLOW__WEBSERVER__COOKIE_SECURE" "$1"
  replace "{{AIRFLOW__WEBSERVER__COOKIE_SAMESITE}}" "$AIRFLOW__WEBSERVER__COOKIE_SAMESITE" "$1"

  # variables -- email
  replace "{{AIRFLOW__EMAIL__EMAIL_BACKEND}}" "$AIRFLOW__EMAIL__EMAIL_BACKEND" "$1"

  # variables -- smtp
  replace "{{AIRFLOW__SMTP__SMTP_HOST}}" "$AIRFLOW__SMTP__SMTP_HOST" "$1"
  replace "{{AIRFLOW__SMTP__SMTP_PORT}}" "$AIRFLOW__SMTP__SMTP_PORT" "$1"
  replace "{{AIRFLOW__SMTP__STARTTLS}}" "$AIRFLOW__SMTP__STARTTLS" "$1"
  replace "{{AIRFLOW__SMTP__SMTP_SSL}}" "$AIRFLOW__SMTP__SMTP_SSL" "$1"
  replace "{{AIRFLOW__SMTP__SMTP_USER}}" "$AIRFLOW__SMTP__SMTP_USER" "$1"
#  replace "{{AIRFLOW__SMTP__SMTP_PASSWORD}}" "$AIRFLOW__SMTP__SMTP_PASSWORD" "$1"
  replace "{{AIRFLOW__SMTP__SMTP_MAIL_FROM}}" "$AIRFLOW__SMTP__SMTP_MAIL_FROM" "$1"

  # variables -- celery
  replace "{{AIRFLOW__CELERY__CELERY_APP_NAME}}" "$AIRFLOW__CELERY__CELERY_APP_NAME" "$1"
  replace "{{AIRFLOW__CELERY__WORKER_CONCURRENCY}}" "$AIRFLOW__CELERY__WORKER_CONCURRENCY" "$1"
  replace "{{AIRFLOW__CELERY__WORKER_AUTOSCALE}}" "$AIRFLOW__CELERY__WORKER_AUTOSCALE" "$1"
  replace "{{AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT}}" "$AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT" "$1"
#  replace "{{AIRFLOW__CELERY__BROKER_URL}}" "$AIRFLOW__CELERY__BROKER_URL" "$1"
#  replace "{{AIRFLOW__CELERY__RESULT_BACKEND}}" "$AIRFLOW__CELERY__RESULT_BACKEND" "$1"
  replace "{{AIRFLOW__CELERY__FLOWER_HOST}}" "$AIRFLOW__CELERY__FLOWER_HOST" "$1"
  replace "{{AIRFLOW__CELERY__FLOWER_URL_PREFIX}}" "$AIRFLOW__CELERY__FLOWER_URL_PREFIX" "$1"
  replace "{{AIRFLOW__CELERY__FLOWER_PORT}}" "$AIRFLOW__CELERY__FLOWER_PORT" "$1"
  replace "{{AIRFLOW__CELERY__FLOWER_BASIC_AUTH}}" "$AIRFLOW__CELERY__FLOWER_BASIC_AUTH" "$1"
  replace "{{AIRFLOW__CELERY__DEFAULT_QUEUE}}" "$AIRFLOW__CELERY__DEFAULT_QUEUE" "$1"
  replace "{{AIRFLOW__CELERY__SYNC_PARALLELISM}}" "$AIRFLOW__CELERY__SYNC_PARALLELISM" "$1"
  replace "{{AIRFLOW__CELERY__CELERY_CONFIG_OPTIONS}}" "$AIRFLOW__CELERY__CELERY_CONFIG_OPTIONS" "$1"
  replace "{{AIRFLOW__CELERY__SSL_ACTIVE}}" "$AIRFLOW__CELERY__SSL_ACTIVE" "$1"
  replace "{{AIRFLOW__CELERY__SSL_KEY}}" "$AIRFLOW__CELERY__SSL_KEY" "$1"
  replace "{{AIRFLOW__CELERY__SSL_CERT}}" "$AIRFLOW__CELERY__SSL_CERT" "$1"
  replace "{{AIRFLOW__CELERY__SSL_CACERT}}" "$AIRFLOW__CELERY__SSL_CACERT" "$1"

  # variables -- scheduler
  replace "{{AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC}}" "$AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC" "$1"
  replace "{{AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC}}" "$AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC" "$1"
  replace "{{AIRFLOW__SCHEDULER__RUN_DURATION}}" "$AIRFLOW__SCHEDULER__RUN_DURATION" "$1"
  replace "{{AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL}}" "$AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL" "$1"
  replace "{{AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL}}" "$AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL" "$1"
  replace "{{AIRFLOW__SCHEDULER__PRINT_STATS_INTERVAL}}" "$AIRFLOW__SCHEDULER__PRINT_STATS_INTERVAL" "$1"
  replace "{{AIRFLOW__SCHEDULER__SCHEDULER_HEATH_CHECK_THRESHOLD}}" "$AIRFLOW__SCHEDULER__SCHEDULER_HEATH_CHECK_THRESHOLD" "$1"
  replace "{{AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY}}" "$AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY" "$1"
  replace "{{AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD}}" "$AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD" "$1"
  replace "{{AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT}}" "$AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT" "$1"
  replace "{{AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY}}" "$AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY" "$1"
  replace "{{AIRFLOW__SCHEDULER__STATSD_ON}}" "$AIRFLOW__SCHEDULER__STATSD_ON" "$1"
  replace "{{AIRFLOW__SCHEDULER__STATSD_HOST}}" "$AIRFLOW__SCHEDULER__STATSD_HOST" "$1"
  replace "{{AIRFLOW__SCHEDULER__STATSD_PORT}}" "$AIRFLOW__SCHEDULER__STATSD_PORT" "$1"
  replace "{{AIRFLOW__SCHEDULER__STATSD_PREFIX}}" "$AIRFLOW__SCHEDULER__STATSD_PREFIX" "$1"
  replace "{{AIRFLOW__SCHEDULER__MAX_THREADS}}" "$AIRFLOW__SCHEDULER__MAX_THREADS" "$1"
  replace "{{AIRFLOW__SCHEDULER__USE_JOB_SCHEDULE}}" "$AIRFLOW__SCHEDULER__USE_JOB_SCHEDULE" "$1"

  # variables -- ldap
  replace "{{AIRFLOW__LDAP__URI}}" "$AIRFLOW__LDAP__URI" "$1"
  replace "{{AIRFLOW__LDAP__USER_FILTER}}" "$AIRFLOW__LDAP__USER_FILTER" "$1"
  replace "{{AIRFLOW__LDAP__USER_NAME_ATTR}}" "$AIRFLOW__LDAP__USER_NAME_ATTR" "$1"
  replace "{{AIRFLOW__LDAP__GROUP_MEMBER_ATTR}}" "$AIRFLOW__LDAP__GROUP_MEMBER_ATTR" "$1"
  replace "{{AIRFLOW__LDAP__SUPERUSER_FILTER}}" "$AIRFLOW__LDAP__SUPERUSER_FILTER" "$1"
  replace "{{AIRFLOW__LDAP__DATA_PROFILER_FILTER}}" "$AIRFLOW__LDAP__DATA_PROFILER_FILTER" "$1"
  replace "{{AIRFLOW__LDAP__BIND_USER}}" "$AIRFLOW__LDAP__BIND_USER" "$1"
#  replace "{{AIRFLOW__LDAP__BIND_PASSWORD}}" "$AIRFLOW__LDAP__BIND_PASSWORD" "$1"
  replace "{{AIRFLOW__LDAP__BASEDN}}" "$AIRFLOW__LDAP__BASEDN" "$1"
  replace "{{AIRFLOW__LDAP__CACERT}}" "$AIRFLOW__LDAP__CACERT" "$1"
  replace "{{AIRFLOW__LDAP__SEARCH_SCOPE}}" "$AIRFLOW__LDAP__SEARCH_SCOPE" "$1"
  replace "{{AIRFLOW__LDAP__IGNORE_MALFORMED_SCHEMA}}" "$AIRFLOW__LDAP__IGNORE_MALFORMED_SCHEMA" "$1"

  # variables -- keytab
  replace "{{AIRFLOW__KERBEROS__CCACHE}}" "$AIRFLOW__KERBEROS__CCACHE" "$1"
  replace "{{AIRFLOW__KERBEROS__PRINCIPAL}}" "$AIRFLOW__KERBEROS__PRINCIPAL" "$1"
  replace "{{AIRFLOW__KERBEROS__REINIT_FREQUENCY}}" "$AIRFLOW__KERBEROS__REINIT_FREQUENCY" "$1"
  replace "{{AIRFLOW__KERBEROS__KINIT_PATH}}" "$AIRFLOW__KERBEROS__KINIT_PATH" "$1"
  replace "{{AIRFLOW__KERBEROS__KEYTAB}}" "$AIRFLOW__KERBEROS__KEYTAB" "$1"

  # variables -- admin
  replace "{{AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS}}" "$AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS" "$1"
}

# deploy config files
function bash_deploy_client_config {
  log "Deploying Client Configuration..."
  prepare_airflow_cfg "$CONF_DIR/airflow-conf/airflow.cfg"
}

# initialize the airflow database backend
function bash_initialize_db_backend {
  log "Initializing DB Backend..."
  exec airflow initdb
}

# upgrade the airflow database backend
function bash_upgrade_db_backend {
  log "Upgrading DB Backend..."
  exec airflow upgradedb
}

# start the airflow scheduler
function bash_start_scheduler {
  log "Starting Airflow Scheduler..."
  exec airflow scheduler
}

# start an airflow webserver
function bash_start_webserver {
  log "Starting Airflow WebServer..."
  exec airflow webserver
}

# start an airflow worker
function bash_start_worker {
  log "Starting Airflow Worker..."
  exec airflow worker
}

# start an airflow kerberos renewer
function bash_start_kerberos_renewer {
  log "Starting Airflow Kerberos Renewer..."
  exec airflow kerberos
}

# start an airflow celery flower
function bash_start_celery_flower {
  log "Starting Airflow Celery Flower..."
  exec airflow flower
}